# LIBRARY

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import math

# EXPLORATION

In [2]:
file_path = "../1.DATASET/cmi_internet.csv"
df=pd.read_csv(file_path)
df.head(3)

,id,Basic_Demos-Enroll_Season,Basic_Demos-Age,Basic_Demos-Sex,CGAS-Season,CGAS-CGAS_Score,Physical-Season,Physical-BMI,Physical-Height,Physical-Weight,...,PCIAT-PCIAT_18,PCIAT-PCIAT_19,PCIAT-PCIAT_20,PCIAT-PCIAT_Total,SDS-Season,SDS-SDS_Total_Raw,SDS-SDS_Total_T,PreInt_EduHx-Season,PreInt_EduHx-computerinternet_hoursday,sii
0,0,Fall,5,0,Winter,51.0,Fall,16.877316,46.0,50.8,...,4.0,2.0,4.0,55.0,NaN,NaN,NaN,Fall,3.0,2.0
1,1,Summer,9,0,NaN,NaN,Fall,14.035590,48.0,46.0,...,0.0,0.0,0.0,0.0,Fall,46.0,64.0,Summer,0.0,0.0
2,2,Summer,10,1,Fall,71.0,Fall,16.648696,56.5,75.6,...,2.0,1.0,1.0,28.0,Fall,38.0,54.0,Summer,2.0,0.0

In [3]:
df.shape

(8460, 82)

## info from columns

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8460 entries, 0 to 8459
Data columns (total 82 columns):
 #   Column                                  Non-Null Count  Dtype
---  ------                                  --------------  -----
 0   id                                      8460 non-null   int64
 1   Basic_Demos-Enroll_Season               8460 non-null   object
 2   Basic_Demos-Age                         8460 non-null   int64
 3   Basic_Demos-Sex                         8460 non-null   int64
 4   CGAS-Season                             7158 non-null   object
 5   CGAS-CGAS_Score                         7034 non-null   float64
 6   Physical-Season                         7858 non-null   object
 7   Physical-BMI                            7591 non-null   float64
 8   Physical-Height                         7595 non-null   float64
 9   Physical-Weight                         7641 non-null   float64
 10  Physical-Waist_Circumference            5624 non-null   float64
 11  Physical-Diastolic_BP                   7528 non-null   float64
 12  Physical-HeartRate                      7539 non-null   float64
 13  Physical-Systolic_BP                    7528 non-null   float64
 14  Fitness_Endurance-Season                6004 non-null   object
 15  Fitness_Endurance-Max_Stage             5480 non-null   float64
 16  Fitness_Endurance-Time_Mins             5478 non-null   float64
 17  Fitness_Endurance-Time_Sec              5478 non-null   float64
 18  FGC-Season                              7891 non-null   object
 19  FGC-FGC_CU                              6943 non-null   float64
 20  FGC-FGC_CU_Zone                         6906 non-null   float64
 21  FGC-FGC_GSND                            5787 non-null   float64
 22  FGC-FGC_GSND_Zone                       5776 non-null   float64
 23  FGC-FGC_GSD                             5787 non-null   float64
 24  FGC-FGC_GSD_Zone                        5776 non-null   float64
 25  FGC-FGC_PU                              6932 non-null   float64
 26  FGC-FGC_PU_Zone                         6895 non-null   float64
 27  FGC-FGC_SRL                             6926 non-null   float64
 28  FGC-FGC_SRL_Zone                        6891 non-null   float64
 29  FGC-FGC_SRR                             6928 non-null   float64
 30  FGC-FGC_SRR_Zone                        6893 non-null   float64
 31  FGC-FGC_TL                              6945 non-null   float64
 32  FGC-FGC_TL_Zone                         6908 non-null   float64
 33  BIA-Season                              6778 non-null   object
 34  BIA-BIA_Activity_Level_num              6636 non-null   float64
 35  BIA-BIA_BMC                             6636 non-null   float64
 36  BIA-BIA_BMI                             6636 non-null   float64
 37  BIA-BIA_BMR                             6636 non-null   float64
 38  BIA-BIA_DEE                             6636 non-null   float64
 39  BIA-BIA_ECW                             6636 non-null   float64
 40  BIA-BIA_FFM                             6636 non-null   float64
 41  BIA-BIA_FFMI                            6636 non-null   float64
 42  BIA-BIA_FMI                             6636 non-null   float64
 43  BIA-BIA_Fat                             6636 non-null   float64
 44  BIA-BIA_Frame_num                       6636 non-null   float64
 45  BIA-BIA_ICW                             6636 non-null   float64
 46  BIA-BIA_LDM                             6636 non-null   float64
 47  BIA-BIA_LST                             6636 non-null   float64
 48  BIA-BIA_SMM                             6636 non-null   float64
 49  BIA-BIA_TBW                             6636 non-null   float64
 50  PAQ_A-Season                            5231 non-null   object
 51  PAQ_A-PAQ_A_Total                       5231 non-null   float64
 52  PAQ_C-Season                            6385 non-null   object
 53  PAQ_C-PAQ_C_Total                       6385 non-null   float64
 54  PCIAT-Season                            2714 non-null   object
 55  PCIAT-PCIAT_01                          2714 non-null   float64
 56  PCIAT-PCIAT_02                          2714 non-null   float64
 57  PCIAT-PCIAT_03                          2714 non-null   float64
 58  PCIAT-PCIAT_04                          2714 non-null   float64
 59  PCIAT-PCIAT_05                          2714 non-null   float64
 60  PCIAT-PCIAT_06                          2714 non-null   float64
 61  PCIAT-PCIAT_07                          2714 non-null   float64
 62  PCIAT-PCIAT_08                          2714 non-null   float64
 63  PCIAT-PCIAT_09                          2714 non-null   float64
 64  PCIAT-PCIAT_10                          2714 non-null   float64
 65  PCIAT-PCIAT_11                          2714 non-null   float64
 66  PCIAT-PCIAT_12                          2714 non-null   float64
 67  PCIAT-PCIAT_13                          2714 non-null   float64
 68  PCIAT-PCIAT_14                          2714 non-null   float64
 69  PCIAT-PCIAT_15                          2714 non-null   float64
 70  PCIAT-PCIAT_16                          2714 non-null   float64
 71  PCIAT-PCIAT_17                          2714 non-null   float64
 72  PCIAT-PCIAT_18                          2714 non-null   float64
 73  PCIAT-PCIAT_19                          2714 non-null   float64
 74  PCIAT-PCIAT_20                          2714 non-null   float64
 75  PCIAT-PCIAT_Total                       2714 non-null   float64
 76  SDS-Season                              4903 non-null   object
 77  SDS-SDS_Total_Raw                       4903 non-null   float64
 78  SDS-SDS_Total_T                         4903 non-null   float64
 79  PreInt_EduHx-Season                     8071 non-null   object
 80  PreInt_EduHx-computerinternet_hoursday  7849 non-null   float64
 81  sii                                     8460 non-null   float64
dtypes: float64(68), int64(3), object(11)
memory usage: 5.3+ MB

In [5]:
for name in df.columns:
    print(name, df[name].isnull().sum())

id 0
Basic_Demos-Enroll_Season 0
Basic_Demos-Age 0
Basic_Demos-Sex 0
CGAS-Season 1302
CGAS-CGAS_Score 1426
Physical-Season 602
Physical-BMI 869
Physical-Height 865
Physical-Weight 819
Physical-Waist_Circumference 2836
Physical-Diastolic_BP 932
Physical-HeartRate 921
Physical-Systolic_BP 932
Fitness_Endurance-Season 2456
Fitness_Endurance-Max_Stage 2980
Fitness_Endurance-Time_Mins 2982
Fitness_Endurance-Time_Sec 2982
FGC-Season 569
FGC-FGC_CU 1517
FGC-FGC_CU_Zone 1554
FGC-FGC_GSND 2673
FGC-FGC_GSND_Zone 2684
FGC-FGC_GSD 2673
FGC-FGC_GSD_Zone 2684
FGC-FGC_PU 1528
FGC-FGC_PU_Zone 1565
FGC-FGC_SRL 1534
FGC-FGC_SRL_Zone 1569
FGC-FGC_SRR 1532
FGC-FGC_SRR_Zone 1567
FGC-FGC_TL 1515
FGC-FGC_TL_Zone 1552
BIA-Season 1682
BIA-BIA_Activity_Level_num 1824
BIA-BIA_BMC 1824
BIA-BIA_BMI 1824
BIA-BIA_BMR 1824
BIA-BIA_DEE 1824
BIA-BIA_ECW 1824
BIA-BIA_FFM 1824
BIA-BIA_FFMI 1824
BIA-BIA_FMI 1824
BIA-BIA_Fat 1824
BIA-BIA_Frame_num 1824
BIA-BIA_ICW 1824
BIA-BIA_LDM 1824
BIA-BIA_LST 1824
BIA-BIA_SMM 1824
BIA-BIA_TBW 1824
PAQ_A-Season 3229
PAQ_A-PAQ_A_Total 3229
PAQ_C-Season 2075
PAQ_C-PAQ_C_Total 2075
PCIAT-Season 5746
PCIAT-PCIAT_01 5746
PCIAT-PCIAT_02 5746
PCIAT-PCIAT_03 5746
PCIAT-PCIAT_04 5746
PCIAT-PCIAT_05 5746
PCIAT-PCIAT_06 5746
PCIAT-PCIAT_07 5746
PCIAT-PCIAT_08 5746
PCIAT-PCIAT_09 5746
PCIAT-PCIAT_10 5746
PCIAT-PCIAT_11 5746
PCIAT-PCIAT_12 5746
PCIAT-PCIAT_13 5746
PCIAT-PCIAT_14 5746
PCIAT-PCIAT_15 5746
PCIAT-PCIAT_16 5746
PCIAT-PCIAT_17 5746
PCIAT-PCIAT_18 5746
PCIAT-PCIAT_19 5746
PCIAT-PCIAT_20 5746
PCIAT-PCIAT_Total 5746
SDS-Season 3557
SDS-SDS_Total_Raw 3557
SDS-SDS_Total_T 3557
PreInt_EduHx-Season 389
PreInt_EduHx-computerinternet_hoursday 611
sii 0

In [9]:
df.values[[1],:]

array([[1, 'Summer', 9, 0, nan, nan, 'Fall', 14.03559028, 48.0, 46.0,
        22.0, 75.0, 70.0, 122.0, nan, nan, nan, 28.0, 'Fall', 3.0, 0.0,
        nan, 2.0, nan, 2.0, 5.0, 0.0, 11.0, 1.0, 11.0, 1.0, 3.0, 0.0,
        'Winter', 2.0, 2.57949, 14.0371, 936.656, 1498.65, 6.01993,
        42.0291, 12.8254, 1.21172, 3.97085, 1.0, 21.0352, 14.974,
        39.4497, 15.4107, 27.0552, 'Winter', 2.01, 'Fall', 2.34, 'Fall',
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 'Fall', 46.0, 64.0,
        'Summer', 0.0, 0.0, 14.035590277777777]], dtype=object)

In [10]:
import pandas as pd

def analizza_attributo(df, colonna, quantili=[0.1,0.25,0.50, 0.75,0.9,0.99]):
    serie = df[colonna]
    
    # Controllo valori uguali a 0
    num_zero = (serie == 0).sum()
    presenza_zero = num_zero > 0
    
    # Controllo valori negativi
    num_negativi = (serie < 0).sum()
    presenza_negativi = num_negativi > 0
    
    # Calcolo range (min e max)
    valore_min = serie.min()
    valore_max = serie.max()
    range_valori = valore_max - valore_min

     # Calcolo quantili
    valori_quantili = serie.quantile(quantili)
    
    # Stampa risultati
    print(f"Analyzed column: {colonna}")
    print(f"Presence of values equal to 0: {presenza_zero}")
    print(f"Number of values equal to 0: {num_zero}")
    print(f"Presence of negative values: {presenza_negativi}")
    print(f"Number of negative values: {num_negativi}")    
    print(f"Minimum value: {valore_min}")
    print(f"Maximum value: {valore_max}")
    print(f"Range (max - min): {range_valori}")

    print(f"\nQuantiles:")
    for q, v in valori_quantili.items():
        print(f"  Q{int(q*100)} ({q}): {v}")


# Esempio di utilizzo
# df = pd.read_csv("dataset.csv")
# analizza_attributo(df, "attributo")

In [12]:
analizza_attributo(df, "BIA-BIA_FFM")

Analyzed column: BIA-BIA_FFM
Presence of values equal to 0: False
Number of values equal to 0: 0
Presence of negative values: False
Number of negative values: 0
Minimum value: 28.9004
Maximum value: 8799.08
Range (max - min): 8770.1796

Quantiles:
  Q10 (0.1): 43.42977098261872
  Q25 (0.25): 50.738330740293144
  Q50 (0.5): 61.0662
  Q75 (0.75): 76.74912499999999
  Q90 (0.9): 96.90124835684448
  Q99 (0.99): 161.14111338448637

## unique values

In [16]:
df['Basic_Demos-Sex'].value_counts()

Basic_Demos-Sex
0    5056
1    3404
Name: count, dtype: int64

In [17]:
df[(df['CGAS-Season']!=df['Physical-Season']) & (df['Physical-Season'].notna()) & (df['CGAS-Season'].notna())].shape

(5076, 85)

## BMI CALCULATOR

In [6]:
df['Physical-BMI_CAL']=(df['Physical-Weight']/(df['Physical-Height']*df['Physical-Height']))*703

In [7]:
round(df['Physical-BMI_CAL'],0)

0       17.0
1       14.0
2       17.0
3       18.0
4        NaN
        ...
8455    16.0
8456    11.0
8457    14.0
8458    17.0
8459    12.0
Name: Physical-BMI_CAL, Length: 8460, dtype: float64

In [8]:
df[['Basic_Demos-Age','Physical-BMI','Physical-BMI_CAL']][(round(df['Physical-BMI_CAL'],0)!=round(df['Physical-BMI'],0)) &(df['Physical-BMI'].notna()) &(df['Physical-BMI_CAL'].notna())]

      Basic_Demos-Age  Physical-BMI  Physical-BMI_CAL
802                 8     17.937682          0.000000
930                 9     17.937682          0.000000
1174                9     17.937682          0.000000
1661               11     17.937682          0.000000
1699               12     17.937682          0.000000
...               ...           ...               ...
8451               14     22.291181         19.817188
8452                6     18.932165         11.558486
8454               16     23.569958         20.434521
8457               10     40.937571         13.509359
8459                7     16.391310         11.601047

[3261 rows x 3 columns]

## BIA-BIA_FFM CALCULATOR

In [13]:
df["BIA-BIA_FFM_check"]=df["BIA-BIA_LST"]+df["BIA-BIA_BMC"]
df[["Physical-Weight","BIA-BIA_FFM","BIA-BIA_LST","BIA-BIA_BMC","BIA-BIA_FFM_check"]][(round(df["BIA-BIA_FFM_check"],0)!=round(df["BIA-BIA_FFM"],0)) & (df["BIA-BIA_FFM_check"].notna()) & (df["BIA-BIA_FFM"].notna())]

,Physical-Weight,BIA-BIA_FFM,BIA-BIA_LST,BIA-BIA_BMC,BIA-BIA_FFM_check
3960,51.2,41.410640,42.634752,3.708782,46.343534
3963,120.6,93.441125,70.259368,7.037091,77.296458
3964,41.4,40.192383,40.830370,5.231689,46.062059
3965,72.2,63.750798,61.924863,5.250973,67.175836
3966,71.7,54.841245,52.644627,-0.555723,52.088904
...,...,...,...,...,...
8448,NaN,44.763927,47.333189,5.263506,52.596695
8451,123.8,93.840014,88.223778,6.682633,94.906411
8454,143.9,115.712153,128.756213,7.492883,136.249096
8455,49.0,42.546078,37.154343,2.625946,39.780289
8457,47.2,51.311561,50.805915,3.990512,54.796427

In [14]:
df[["Physical-Weight","BIA-BIA_FFM","BIA-BIA_LST","BIA-BIA_BMC","BIA-BIA_FFM_check"]][(df["BIA-BIA_FFM"]>110) & (round(df["BIA-BIA_FFM_check"],0)!=round(df["BIA-BIA_FFM"],0)) & (df["BIA-BIA_FFM_check"].notna()) & (df["BIA-BIA_FFM"].notna())]

,Physical-Weight,BIA-BIA_FFM,BIA-BIA_LST,BIA-BIA_BMC,BIA-BIA_FFM_check
4019,122.2,116.289774,85.222832,4.359188,89.582020
4045,146.6,121.517983,99.456650,6.773174,106.229824
4077,107.8,110.233166,120.333374,5.533802,125.867176
4113,60.3,3529.994813,48.699959,5.531023,54.230983
4151,171.8,141.237019,118.040959,7.815532,125.856491
...,...,...,...,...,...
8296,142.7,5871.041700,69.055352,5.258480,74.313832
8304,144.9,117.224042,113.233700,7.190622,120.424322
8315,133.7,140.840803,169.727014,6.112870,175.839884
8420,NaN,124.872351,112.126746,6.476812,118.603559
8454,143.9,115.712153,128.756213,7.492883,136.249096

In [16]:
df[["Physical-Weight","BIA-BIA_FFM","BIA-BIA_LST","BIA-BIA_BMC","BIA-BIA_FFM_check"]][df["BIA-BIA_FFM"] >100]

,Physical-Weight,BIA-BIA_FFM,BIA-BIA_LST,BIA-BIA_BMC,BIA-BIA_FFM_check
22,178.0,107.486000,102.335000,5.150680,107.485680
55,164.4,130.513000,133.690000,-3.177770,130.512230
72,152.4,127.810000,129.130000,-1.320460,127.809540
96,157.8,105.930000,98.667600,7.262890,105.930490
139,170.8,112.534000,106.506000,6.028140,112.534140
...,...,...,...,...,...
8388,121.0,131.508767,NaN,137.162260,NaN
8420,NaN,124.872351,112.126746,6.476812,118.603559
8422,142.9,109.576416,105.506088,6.866089,112.372177
8435,133.4,104.530262,106.807622,7.313856,114.121478
8454,143.9,115.712153,128.756213,7.492883,136.249096

## BIA-BIA_TBW CALCULATOR

In [15]:
df["BIA-BIA_TBW_check"]=df["BIA-BIA_ECW"]+df["BIA-BIA_ICW"]
df[["BIA-BIA_TBW","BIA-BIA_ECW","BIA-BIA_ICW","BIA-BIA_TBW_check"]][(round(df["BIA-BIA_TBW_check"],0)!=round(df["BIA-BIA_TBW"],0)) & (df["BIA-BIA_TBW_check"].notna()) & (df["BIA-BIA_TBW"].notna())]

      BIA-BIA_TBW  BIA-BIA_ECW  BIA-BIA_ICW  BIA-BIA_TBW_check
3960    36.362510     8.450677    25.439474          33.890151
3961    41.015867    19.970088    25.863285          45.833373
3963    54.215776    36.478587    30.203444          66.682031
3964    27.089703     7.175487    22.511098          29.686585
3965   178.097521    17.495067    28.994338          46.489405
...           ...          ...          ...                ...
8454    91.990256    43.422553    45.704166          89.126719
8456    36.475662    13.855099    22.690881          36.545980
8457    35.106855    14.293348    30.581230          44.874578
8458    57.530686    30.298032    30.387635          60.685667
8459    27.096538     5.158159    20.548754          25.706913

[2291 rows x 4 columns]