In [10]:
import pandas as pd

In [11]:
file_path = "../1.DATASET/CMI_FINAL_OD.csv"
df=pd.read_csv(file_path)

In [12]:
df.describe([.01,.1,.2,.3,.4,.5,.6,.7,.8,.9,.95])

,id,Basic_Demos-Age,Basic_Demos-Sex,Physical-BMI,Physical-Height,Physical-Weight,Physical-MAP_CAL,FGC-FGC_CORE_CAL,FGC-FGC_GS_CAL,FGC-FGC_SR_CAL,BIA-BIA_Activity_Level_num,BIA-BIA_BMC,BIA-BIA_DEE,BIA-BIA_FFM,BIA-BIA_Fat,BIA-BIA_Frame_num,BIA-BIA_SMM,BIA-BIA_TBW,sii
count,8396.000000,8396.000000,8396.000000,8396.000000,8396.000000,8396.000000,8396.000000,8396.000000,8396.000000,8396.000000,8396.000000,8396.000000,8396.000000,8396.000000,8396.000000,8396.000000,8396.000000,8396.000000,8396.000000
mean,4233.378037,10.209147,0.403168,19.311053,56.378636,91.344985,84.589321,15.511726,20.180317,8.406537,2.770962,4.850340,1896.475995,70.475201,20.869784,1.711887,29.835548,44.453177,0.441162
std,2443.288170,3.550147,0.490563,4.328157,7.727730,40.289785,9.666656,11.490677,5.530166,2.023177,0.819837,2.244613,494.083184,30.565676,16.031960,0.562269,11.790774,13.717257,0.728549
min,0.000000,5.000000,0.000000,8.522436,33.000000,31.800000,37.666667,0.500000,0.100000,1.000000,1.000000,0.009889,1073.450000,1.181133,0.026117,1.000000,0.590566,20.589200,0.000000
1%,83.950000,5.000000,0.000000,13.730469,41.616667,40.197876,65.333333,1.000000,9.700000,3.000000,1.000000,1.819422,1183.139000,27.892909,2.096686,1.000000,12.793476,21.776899,0.000000
10%,846.500000,6.000000,0.000000,15.424007,47.000000,50.715362,74.666667,4.500000,16.300000,6.000000,2.000000,2.681194,1445.743382,41.349648,7.037178,1.000000,18.024600,30.631881,0.000000
20%,1693.000000,7.000000,0.000000,16.141329,49.580000,58.328597,78.333333,6.280570,17.883041,7.426384,2.000000,3.075206,1555.462112,47.642333,9.627504,1.000000,21.140700,34.510452,0.000000
30%,2542.500000,8.000000,0.000000,16.836794,52.000000,66.437028,80.833333,9.540221,18.125000,7.682875,2.000000,3.419664,1653.057381,53.090241,11.642934,1.000000,23.992969,38.443686,0.000000
40%,3392.000000,9.000000,0.000000,17.400000,54.500000,74.200000,82.152821,10.568299,18.500000,8.123333,3.000000,3.899434,1738.411328,58.174248,13.546400,2.000000,25.273100,41.616667,0.000000
50%,4234.500000,10.000000,0.000000,17.937682,55.050000,77.600000,83.333333,12.787145,18.613018,8.500000,3.000000,4.485385,1802.069977,61.848628,15.811750,2.000000,25.653042,42.380000,0.000000
60%,5080.000000,10.000000,1.000000,18.742090,57.000000,87.600000,84.630603,14.662915,18.909726,8.749076,3.000000,4.967841,1897.920000,67.324900,17.948622,2.000000,28.201500,42.500000,0.000000
70%,5926.500000,12.000000,1.000000,20.094411,60.000000,103.444642,86.500000,18.500000,20.625000,9.000000,3.000000,5.503839,2015.765309,77.051378,23.059342,2.000000,33.828494,44.100000,1.000000
80%,6771.000000,13.000000,1.000000,22.362821,64.000000,122.400000,89.333333,23.166667,22.200000,9.500000,3.000000,6.086403,2190.720000,90.685881,31.813500,2.000000,37.823534,51.708412,1.000000
90%,7618.500000,16.000000,1.000000,24.675884,67.470000,148.641497,95.000000,28.000000,26.562500,10.500000,4.000000,7.446993,2401.570000,112.398406,41.598406,2.000000,45.266590,62.712943,2.000000
95%,8038.250000,17.000000,1.000000,27.623302,70.000000,169.247833,101.666667,36.500000,28.856250,11.750000,4.000000,9.586950,2677.670000,128.723960,50.859676,3.000000,54.089200,73.654100,2.000000
max,8459.000000,22.000000,1.000000,59.132048,78.500000,291.534719,164.333333,150.000000,115.100000,21.000000,5.000000,42.127364,17311.200000,268.694823,153.820000,3.000000,89.488400,132.884000,3.000000

In [13]:
#df.describe([.01,.1,.2,.3,.4,.5,.6,.7,.8,.9,.98])
df[df["BIA-BIA_DEE"]>4000]

,id,Basic_Demos-Age,Basic_Demos-Sex,Physical-BMI,Physical-Height,Physical-Weight,Physical-MAP_CAL,FGC-FGC_CORE_CAL,FGC-FGC_GS_CAL,FGC-FGC_SR_CAL,BIA-BIA_Activity_Level_num,BIA-BIA_BMC,BIA-BIA_DEE,BIA-BIA_FFM,BIA-BIA_Fat,BIA-BIA_Frame_num,BIA-BIA_SMM,BIA-BIA_TBW,sii
1413,1423,20,0,23.211846,69.000000,157.200000,89.333333,12.000000,25.583333,8.175000,5.0,7.109900,4140.310000,126.012100,31.187900,1.0,68.046400,94.087700,0.0
1688,1702,15,0,20.754316,66.000000,128.600000,101.000000,60.000000,44.700000,12.000000,5.0,6.796640,4038.590000,121.497790,7.102210,2.0,63.020000,92.544800,1.0
2183,2202,14,0,23.041184,70.000000,160.600000,74.000000,42.000000,39.450000,8.500000,5.0,7.832950,4517.130000,142.735300,17.864700,2.0,68.223200,107.092000,1.0
2278,2299,13,1,24.825467,65.000000,149.200000,89.333333,64.000000,30.700000,11.500000,2.0,10.514600,5400.270000,119.971214,29.228786,2.0,83.837450,55.600000,0.0
2388,2410,20,0,31.628724,71.000000,226.800000,86.666667,19.630435,20.625000,8.175000,4.0,8.684280,4166.930000,153.612000,73.188000,3.0,77.463700,113.276000,0.0
2455,2478,17,0,21.100849,72.000000,155.600000,103.666667,26.500000,28.795679,8.060190,4.0,9.302910,4632.300000,106.294714,49.305286,3.0,53.147357,132.884000,2.0
2467,2490,18,0,27.255221,67.300000,175.600000,93.000000,23.310811,26.463732,8.003205,3.0,11.945600,6779.050000,146.371214,29.228786,2.0,83.837450,58.355000,2.0
2742,2770,9,0,16.947321,56.000000,75.600000,77.333333,5.000000,20.625000,5.250000,3.0,8.169450,5296.720000,60.659833,14.940167,1.0,30.329917,55.600000,0.0
3061,3091,14,0,18.330074,67.500000,118.800000,86.000000,50.000000,27.200000,9.500000,3.0,9.069260,4007.370000,102.559100,16.240900,2.0,83.837450,48.333333,0.0
3116,3147,8,0,16.110417,48.000000,52.800000,65.666667,30.000000,18.526452,10.000000,4.0,6.491210,6467.970000,43.646389,9.153611,1.0,21.823194,42.240000,0.0
3476,3511,13,1,23.605261,61.500000,127.000000,74.666667,21.000000,23.100000,12.000000,2.0,2.681194,17311.200000,100.853640,26.146360,2.0,83.837450,66.700000,2.0
3595,3630,13,1,18.668340,65.750000,114.800000,103.333333,21.493846,22.080423,7.426384,4.0,9.484850,5717.710000,85.571214,29.228786,3.0,83.837450,52.600000,0.0
3693,3729,11,1,17.937682,55.000000,77.185617,83.333333,1.000000,14.700000,15.500000,4.0,7.502740,6023.420000,57.475797,19.709820,2.0,28.737898,55.507143,0.0
4020,4057,18,0,23.843858,68.820000,160.638830,87.833333,23.310811,18.125000,10.000000,2.0,7.078356,4310.299230,74.842185,85.796645,2.0,53.647846,62.965746,0.0
4193,4230,6,0,20.455032,67.540000,132.729346,87.666667,31.000000,26.275000,6.500000,2.0,3.997907,11248.196197,101.154100,31.575246,2.0,37.698900,32.248021,1.0
5055,5098,13,1,15.515043,71.180000,111.818490,79.166667,55.000000,22.080423,10.500000,4.0,5.757605,5833.216001,100.807717,11.010773,2.0,44.474777,48.686405,1.0
5196,5241,17,0,23.551383,70.260000,165.377864,89.833333,26.500000,32.375000,7.500000,4.0,2.681194,4710.810431,133.579215,31.798649,1.0,55.545574,103.104618,0.0
6395,6448,16,1,16.627113,67.260000,106.997896,75.166667,25.316850,26.714087,8.464640,5.0,6.165710,5740.372351,72.680351,34.317545,1.0,43.386981,50.538606,0.0
7514,7577,10,0,33.917105,57.310000,158.461682,87.166667,9.000000,16.840263,7.682875,3.0,6.098528,10452.893971,140.513060,17.948622,2.0,39.294548,57.961857,0.0
7561,7624,16,0,16.771132,69.220000,114.306323,96.166667,25.316850,24.675000,6.000000,3.0,7.249095,6193.726933,105.047751,9.258572,2.0,49.143001,66.655840,0.0
7718,7781,10,0,17.250622,67.085714,110.435709,82.333333,34.000000,20.025000,6.000000,3.0,4.864686,4728.276819,94.510690,15.925019,2.0,37.901036,44.231871,0.0
8300,8364,13,1,22.000789,64.910000,131.857899,82.333333,21.493846,22.080423,4.500000,3.0,5.602193,7280.658045,94.468240,37.389658,2.0,46.398177,48.056131,0.0

In [14]:
df = df[df["BIA-BIA_DEE"]<=4000]

In [15]:
df.to_csv('../1.DATASET/CMI_FINAL_OD_1.csv', index=False)